config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  root 'items#index'
  resources :cards, only: [:new, :index, :create, :destroy]
  resources :categories, only: [:index, :show]
  resources :users, only: [:index, :new, :show, :create] do
    member do
      get 'logout'
    end
  end

  namespace :items do
    resources :searches, only: :index
  end

  resources :items do
    resource :bookmarks, only:[:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      get 'buy'
      post 'pay'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection  do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials
  has_many :items
  has_many :bookmarks
  has_many :bookmark_items, through: :bookmarks, source: :item
  has_many :users, through: :items

  has_many :comments

  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d!@#\$%\^\&*\)\(+=._-]{7,128}\z/i
  VALID_POSTAL_CODE = /\A\d{7}\z/

  # ユーザー新規登録時のバリデーション

  ## 一般
  validates :nickname,                     presence: true, length: { maximum: 20 }
  validates :email,                        presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX,       message: 'のフォーマットが不適切です'}
  validates :postal_code,                  presence: true, length: { maximum: 8 }, format: { with: VALID_POSTAL_CODE, message: 'のフォーマットが不適切です' }
  validates :municipality,                 presence: true, length: { maximum: 50 }
  validates :address,                      presence: true, length: { maximum: 100 }

  ## 名前全角
  validates :family_name,                  presence: true, length: { maximum: 35 }
  validates :user_name,                    presence: true, length: { maximum: 35 }

  ## 名前カナ
  validates :family_name_kana,             presence: true, format: {with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/,       message: "全角カタカナのみで入力して下さい"}
  validates :user_name_kana,               presence: true, format: {with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/,       message: "全角カタカナのみで入力して下さい"}
  validates :destination_family_name_kana, presence: true, format: {with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/,       message: "全角カタカナのみで入力して下さい"}
  validates :destination_name_kana,        presence: true, format: {with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/,       message: "全角カタカナのみで入力して下さい"}

  ## パスワード
  validates :password,                     presence: true, length: { in: 7..128 }, format: { with: VALID_PASSWORD_REGEX, message: 'は英字と数字両方を含むパスワードを設定してください'}
  # validates :password_confirmation,        presence: true, length: { in: 7..128 }, format: { with: VALID_PASSWORD_REGEX, message: 'は英字と数字両方を含むパスワードを設定してください'}

  validates :phone_number,                 length: { maximum: 15,message: "電話番号に誤りがあります"}

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_category, except: [:index]

  def index
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to root_path
    else
      flash[:notice] = '入力項目に不備があります'
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @items = Item.where(seller_id: current_user.id).order("created_at DESC")
    @images = Image.includes(:item)
    @user = User.find(params[:id])
    @bookmark_items = @user.bookmark_items.order("created_at DESC")
  end

  private
  def user_params
    params.require(:user).permit(:nickname,:email,:password,:password_confirmation,:family_name,:family_name_kana,:user_name,:user_name_kana,:birthday, :destination_family_name, :destination_family_name_kana, :destination_name, :destination_name_kana, :postal_code, :prefectures, :municipality, :address, :apartment_room_namber, :phone_number)
  end

  def set_category
    @parents = Category.where(ancestry: nil)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.haml
.user-show-page__side
  %h3.user-show-page__side__setting-top
    個人情報設定
  %ul.user-show-page__side__setting-list
    %li
      =link_to user_path(current_user) ,class:"user-show-page__side__setting-list__item" do
        プロフィール
    %li
      =link_to cards_path ,class:"user-show-page__side__setting-list__item" do
        支払い方法
    %li
      =link_to logout_user_path(current_user) ,class:"user-show-page__side__setting-list__item" do
        ログアウト

   

app/views/users/index.html.haml
=render "items/logo-header"
.registration__wrap
  %p 新規会員登録
  .registration__box
    = link_to 'Facebookで登録', user_facebook_omniauth_authorize_path, method: :post, class: "facebook"
    = link_to 'Googleで登録', user_google_oauth2_omniauth_authorize_path, method: :post, class: "google"
    = link_to 'メールアドレスで登録', new_user_registration_path, class: "email"
=render "items/footer"

app/views/users/logout.html.haml
=render "/items/header"
- breadcrumb :logout
= render "layouts/breadcrumbs"
.user-logout
  =render "sidebar"
  .user-logout__btn
    =link_to sign_out_path, class:"user-logout__btn__red" do
      ログアウト
=render "/items/footer"

app/views/users/show.html.haml
=render "/items/header"
- breadcrumb :mypage
= render "layouts/breadcrumbs"
.user-show
  =render "sidebar"
  .user-show-page
    .user-show-page__main
      %section.user-show-page__main__icon
        =link_to"#",class:"user-show-page__main__icon__link" do
          %figure
            = image_tag asset_path 'yu-za-.jpg', alt: "", height: "60", width: "60", class: "user-show-page__main__icon__link__photo"
          %h2.user-show-page__main__icon__link__name
            = current_user.nickname
          .user-show-page__main__icon__link__situation
            %div
              %span.user-show-page__main__icon__link__situation__good
            %div.good-sukima
              出品数
              %span.user-show-page__main__icon__link__situation__item
                = @items.length
      %section.user-show-page__main__todo
        .user-show-page__main__todo__under-tabs
          .user-show-page__main__todo__under-tabs__product-list
            .user-show-page__main__todo__under-tabs__product-list__title 
              お気に入り一覧
            .user-show-page__main__todo__under-tabs__product-list__contents
              - @bookmark_items.each do |b|
              - break if @items.nil?
                .user-show-page__main__todo__under-tabs__product-list__contents__content
                  = link_to image_tag(@images.find_by(item_id:[b.id]).image_url, class:"img" ), item_path(b)
                  -if b.buyer_id.present?
                    .photo-line-li__sold
                      .photo-line-li__sold__inner SOLD
                  .user-show-page__main__todo__under-tabs__product-list__contents__content__body
                    .user-show-page__main__todo__under-tabs__product-list__contents__content__body__name
                      = b.title
                    .user-show-page__main__todo__under-tabs__product-list__contents__content__body__text
                      = converting_to_jpy(b.price)
                      %span (税込)
                    .user-show-page__main__todo__under-tabs__product-list__contents__content__body__favorite
                      %i.fas.fa-star
                      = b.bookmarks.length
            .user-show-page__main__todo__under-tabs__product-list__title 
              出品商品一覧
            .user-show-page__main__todo__under-tabs__product-list__contents
              - @items.each do |b|
              - break if @items.nil?
                .user-show-page__main__todo__under-tabs__product-list__contents__content
                  = link_to image_tag(@images.find_by(item_id:[b.id]).image_url, class:"img" ), item_path(b)
                  -if b.buyer_id.present?
                    .photo-line-li__sold
                      .photo-line-li__sold__inner SOLD
                  .user-show-page__main__todo__under-tabs__product-list__contents__content__body
                    .user-show-page__main__todo__under-tabs__product-list__contents__content__body__name
                      = b.title
                    .user-show-page__main__todo__under-tabs__product-list__contents__content__body__text
                      = converting_to_jpy(b.price)
                      %span (税込)
                    .user-show-page__main__todo__under-tabs__product-list__contents__content__body__favorite
                      %i.fas.fa-star
                      = b.bookmarks.count
=render "/items/footer"