config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  root 'items#index'
  resources :cards, only: [:new, :index, :create, :destroy]
  resources :categories, only: [:index, :show]
  resources :users, only: [:index, :new, :show, :create] do
    member do
      get 'logout'
    end
  end

  namespace :items do
    resources :searches, only: :index
  end

  resources :items do
    resource :bookmarks, only:[:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      get 'buy'
      post 'pay'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection  do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks

# アイテム出品、編集のバリデーション
  validates :title,              presence: true, length: { maximum: 40 }       # 商品名。文字あるか。文字数40以下。
  validates :content,            presence: true, length: { maximum: 1000 }     # 商品の説明。文字あるか。文字数1000以下。
  validates :price,              numericality: {greater_than_or_equal_to: 300} # 値段。300円以上。
  validates :price,              numericality: {less_than_or_equal_to: 9999999}# 値段。9999999以上。
  validates :status_id,          numericality: {only_interger: true}           # 商品状態。数値のあるか。
  validates :delivery_method_id, numericality: {only_interger: true}           # 配達方法。
  validates :prefecture_id,      numericality: {only_interger: true}           # 配達元の地域。
  validates :delivery_days_id,   numericality: {only_interger: true}           # 配達までの日数。
  validates :delivery_charge_id, numericality: {only_interger: true}           # 配達料の負担。
  validates_associated :images
  validates :images,             presence: true                                # 写真。
  validates :category_id,        numericality: {only_interger: true}           # カテゴリー。


  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :delivery_days
  belongs_to_active_hash :delivery_method
  belongs_to_active_hash :status
  
  def self.search(search)
    return Item.all unless search
    Item.where('title LIKE(?)', "%#{search}%")
  end
end

app/controllers/items/searches_controller.rb
class Items::SearchesController < ApplicationController
  before_action :set_category
  def index
    @keyword = params[:keyword]
    @category_parent_array = ["---"]
    @category_parent_array.concat(@parents.pluck(:name))
    if params[:q].present?
      @q = Item.ransack(params[:q])
      @items = @q.result(distinct: true).page(params[:page]).per(12).order("created_at DESC")
    else
      params[:q] = { sorts: 'id desc' }
      @q = Item.ransack(params[:q])
      @items = Item.search(params[:keyword]).page(params[:page]).per(12).order("created_at DESC")
    end
  end

  private

  def set_category
    @parents = Category.where(ancestry: nil)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:buy, :pay, :show, :edit, :update, :destroy]
  before_action :set_category, only: [:index, :new, :show, :edit]
  before_action :login_in_user,  except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :my_item_check, only: [:buy, :pay]
  before_action :buy_item_check, only: [:buy, :pay]

  def buy
    @image = @item.images[0].image_url
    @seller = User.find(@item.seller_id)
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
    if @card.blank?
      flash[:notice] = '購入にはクレジットカード登録が必要です'
      redirect_to new_card_url
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(customer.default_card)
      @card_brand = @card_info.brand
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3)

      case @card_brand
      when "Visa"
        @card_image = "credit-visa.svg"
      when "JCB"
        @card_image = "credit-jcb.svg"
      when "MasterCard"
        @card_image = "credit-master-card.svg"
      when "American Express"
        @card_image = "credit-american_express.svg"
      when "Diners Club"
        @card_image = "credit-dinersclub.svg"
      when "Discover"
        @card_image = "credit-discover.svg"
      when "Saison"
        @card_image = "credit-saison-card.svg"
      end
    end
  end

  def pay
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
    if @card.blank?
      redirect_to new_card_url
      flash[:notice] = '購入にはクレジットカード登録が必要です'
    else
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      Payjp::Charge.create(
      amount: @item.price,
      customer: @card.customer_id,
      currency: 'jpy',
      )
      if @item.update(buyer_id: current_user.id)
        flash[:notice] = '購入しました'
        redirect_to root_url
      else
        flash[:notice] = '購入に失敗しました'
        redirect_to item_url(@item)
      end
    end
  end

  def index
    @items = Item.order(id: :desc).where(buyer_id:nil)
    @images = Image.includes(:item)
  end

  def new
    @item = Item.new
    @item.images.new
    @category_parent_array = ["---"]
    @category_parent_array.concat(@parents.pluck(:name))
  end

  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = '出品しました'
      redirect_to root_url
    else
      flash[:notice] = '必須項目を入力してください'
      redirect_to new_item_url
    end
  end

  def show
    @items = Item.all
    @images = @item.images
    @image = @item.images[0].image_url
    @seller = User.find(@item.seller_id)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
    @items = Item.all
    @images = @item.images
    @image = @item.images[0].image_url
    @seller = User.find(@item.seller_id)
    grandchild_category = @item.category
    child_category = grandchild_category.parent
    @category_parent_array = ["---"]
    @category_parent_array.concat(@parents.pluck(:name))
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
  end

  def update
    if user_signed_in? && current_user.id == @item.seller_id
      if @item.update(item_params)
        flash[:notice] = '商品の情報を編集しました'
        redirect_to item_path
      else
        flash[:notice] = '必須項目を入力してください'
        redirect_to edit_item_path
      end
    end
  end

  def destroy
    if user_signed_in? && current_user.id == @item.seller_id
      if @item.destroy
        flash[:notice] = '商品を削除しました'
        redirect_to root_url
      else
        flash[:notice] = '削除出来ませんでした'
        redirect_to item_url
      end
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_category
    @parents = Category.where(ancestry: nil)
  end

  def login_in_user
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to sign_in_url
    end
  end

  def correct_user
    unless current_user.id == @item.seller_id
    flash[:alert] = "アクセスできません"
    redirect_to root_url
    end
  end

  def item_params
    params.require(:item).permit(:title, :content, :price, :status_id, :prefecture_id, :delivery_days_id, :delivery_charge_id, :category_id, :delivery_method_id, :seller_id, images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def my_item_check
    if user_signed_in? && current_user.id == @item.seller_id
      flash[:alert] = "自分で出品した商品は購入出来ません。"
      redirect_to root_url
    end
  end

  def buy_item_check
    if @item.buyer_id.present?
      flash[:alert] = "購入済みの商品です。"
      redirect_to root_url
    end
  end

end

app/helpers/items/searches_helper 2.rb
module Items::SearchesHelper
end

app/helpers/items/searches_helper.rb
module Items::SearchesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited)}円"
  end
end

app/views/items/_appBanner.html.haml
.app-banner
  .app-banner__box
    %p.app-banner__box--title だれでもかんたん、人生を変えるフリマアプリ
    %p.app-banner__box--text 今すぐ無料ダウンロード!
    .link-box
      = link_to '', "#", class: "app-link", style: "display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2012-06-28&kind=iossoftware&bubble=ios_apps)"
      = link_to image_tag('https://play.google.com/intl/en_us/badges/static/images/badges/ja_badge_web_generic.png', width: '155'), "#"

app/views/items/_footer.html.haml
.footer
  %ul.footer__contents
    %li.footer__contents__content
      = link_to 'FURIMAについて', "#", class:"footer__contents__content--head"
      = link_to '会社概要（運営会社）', "#", class:"footer__contents__content--link"
      = link_to 'プライバシーポリシー', "#", class:"footer__contents__content--link"
      = link_to 'FURIMA利用規約', "#", class:"footer__contents__content--link"
      = link_to 'ポイントに関する特約', "#", class:"footer__contents__content--link"
    %li.footer__contents__content
      = link_to 'FURIMAを見る', "#", class:"footer__contents__content--head"
      = link_to 'カテゴリ一覧',  categories_path, class:"footer__contents__content--link"
      = link_to 'ブランド一覧', "#", class:"footer__contents__content--link"
    %li.footer__contents__content
      = link_to 'ヘルプ＆ガイド', "#", class:"footer__contents__content--head"
      = link_to 'FURIMAガイド', "#", class:"footer__contents__content--link"
      = link_to 'FURIMAロゴ利用ガイドライン', "#", class:"footer__contents__content--link"
      = link_to 'お知らせ', "#", class:"footer__contents__content--link"
  .footer__logo
    = image_tag asset_path 'logo-white.png'
    %p © FURIMA

app/views/items/_form.html.haml
%main.single-main
  %section.sell-container
    .sell-container__inner
      %h2.single-container__head
        商品の情報を入力
      = form_with model: @sell,url:sells_path, class:"sell-container__form", local:true do |f|
            = f.label "商品名"
            = f.text_field :name,class: "sell-content__input input-default", placeholder: "商品名（必須 40文字まで)"
            = f.label "商品の説明"
            = f.text_area :info,class:"sell-content__desc_textarea textarea-default",rows:"5" ,placeholder:"商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
            = f.label "カテゴリー"
            = f.label "商品の状態"
            = f.select :status, Product.statuses.keys, {}, class: "sell-content__select-default"
            = f.label "配送料の負担"
            = f.collection_select :delivery_fee_owner_id, DeliveryFeeOwner.all,:id, :delivery_fee_owner, {prompt: "---"},{class:"sell-content__select-default",id:"delivery_fee_owner"
            //jqueryで:delivery_fee_ownersの値によって表示するセレクトボックスを変動させる。
            = f.label "配送の方法"
            = render partial: 'shipping_method',locals: {delivery_fee_owner_id: DeliveryFeeOwner.first.id}
            = f.label "価格"
            = f.text_field :price, class:"input-default",placeholder:"例）300"
            = f.submit "出品する" ,class:"sell-content__btn-red"

app/views/items/_header.html.haml
.header
  .header__main
    .header__main__upper-box
      = link_to image_tag('logo.png', width: '140', height: `40.55`, class: 'logo'), root_path

      .header__main__upper-box__search-box
        = form_with(url: items_searches_path, local: true, method: :get) do |f|
          = f.text_field :keyword, class: "search", placeholder: 'キーワードから探す', value: params[:keyword]
          .send-btn
            = image_submit_tag 'icon-search 1.png', class: "btn"
    .header__main__lower-box
      .header__main__lower-box__left-list
        = image_tag 'icon_category.png', height: '16', width: '16', class:"icon"
        .category-link
          = link_to 'カテゴリ一覧', categories_path, class: "link"
          %ul.category1
            - @parents.each do |parent|
              %li.parent__list
                = link_to parent.name ,category_path(parent)
                %ul.category2
                  - parent.children.each do |child|
                    %li.child__list
                      = link_to child.name ,category_path(child)
                      %ul.category3
                        - child.children.each do |grandchild|
                          %li.grandchild__list
                            = link_to grandchild.name ,category_path(grandchild)
        = image_tag 'icon_brand.png', height: '16', width: '16', class:"icon"
        = link_to 'ブランド', "#", class:"brand-link"
      .right-list
        - if user_signed_in?
          = link_to "マイページ", user_path(current_user), class: "right-list__btn"
          = link_to "ログアウト", logout_user_path(current_user), class: "right-list__btn"
        - else
          = link_to 'ログイン', new_user_session_path, class:"right-list__btn"
          = link_to '新規会員登録', users_path, class:"right-list__btn"

app/views/items/_logo-header.html.haml
.logo-box
  = link_to image_tag("logo.png", width:"170", alt:"logo"), root_path

app/views/items/_t-user-show-sidebar.html.haml
.user-show-page__side
  %nav.user-show-page__side__box
    %h3.user-show-page__side__box__setting-top
      -# 設定
      個人情報設定
    %ul.user-show-page__side__box__setting-list
      %li
        =link_to"#",class:"user-show-page__side__box__setting-list__item" do
          プロフィール
      %li
        =link_to"#",class:"user-show-page__side__box__setting-list__item" do
          発送元•お届け先住所変更
      %li
        =link_to"#",class:"user-show-page__side__box__setting-list__item" do
          支払い方法   
      %li
        =link_to"#",class:"user-show-page__side__box__setting-list__item" do
          メール/パスワード
      %li
        =link_to"#",class:"user-show-page__side__box__setting-list__item" do
          本人情報
      %li
        =link_to"#",class:"user-show-page__side__box__setting-list__item" do
          電話番号確認
      %li
        =link_to"#",class:"user-show-page__side__box__setting-list__item" do
          ログアウト

app/views/items/buy.html.haml
.buy-header
  = link_to image_tag('logo.png', width: '185', alt: 'logo', class: "buy-header__logo"),root_path
.buy-main
  .buy-container
    .buy-container__title
      購入内容の確認
    .buy-container__item
      .buy-container__item__box
        = image_tag "#{@image}", class:'buy-container__item__box__img', size: "60x80", alt: "test"
        .buy-container__item__box__detail
          .buy-container__item__box__detail__name
            #{@item.title}
          .buy-container__item__box__detail__price
            #{converting_to_jpy(@item.price)} (税込) #{@item.delivery_charge.name}
    .buy-container__form-box
      .buy-container__form-box__price
        .buy-container__form-box__price__left
          支払い金額
        .buy-container__form-box__price__right
          #{converting_to_jpy(@item.price)}
      .buy-container__form-box__payment
        .buy-container__form-box__payment__method
          .buy-container__form-box__payment__method__left
            支払い方法
          = link_to('変更', cards_path, {class: 'buy-container__form-box__payment__method__right'})
        .buy-container__form-box__payment__card-info
          クレジットカード
          %br
          = "**** **** **** " + @card_info.last4 
          %br
          有効期限
          = @exp_month + " / " + @exp_year
          %p
            = image_tag "#{@card_image}",width:'34',height:'20', alt:'credit-card', class: 'card-img'
      .buy-container__form-box__delivery
        .buy-container__form-box__delivery__method
          .buy-container__form-box__delivery__method__left
            配送先
          = link_to('変更', '#', {class: 'buy-container__form-box__delivery__method__right'})
        .buy-container__form-box__delivery__user-info
          〒#{@seller.postal_code}
          %br #{@seller.address}
          #{@seller.nickname}
      = form_with url: pay_item_path(@item), id: "buy-form" do |f|
        = f.submit "購入する", class: "buy-btn"
= render "footer"

app/views/items/show.html.haml
=render "header"
.show-main
  .show-main__content-left
  .show-main__content-right
    .show-main__content-top

      .show-main__content-top__item-box
        %h2.show-main__content-top__item-box__name
          #{@item.title}
        .show-main__content-top__item-box__body
          %ul.photo-line-ul
            %li.photo-line-li
              = image_tag "#{@images[0].image}", alt: '', class: 'photo-big'
              -if @item.buyer_id.present?
                .photo-line-li__sold
                  .photo-line-li__sold__inner SOLD
          %ul.photo-line-ul-under
            - [1,2,3].each do |i|
            - break if @images[i].nil?
              %li.photo-line-li-under
                = image_tag "#{@images[i].image}", alt: 'images', class: 'photo-small'
        .show-main__content-top__item-box__pricebox
          %span.show-main__content-top__item-box__pricebox__price
            #{converting_to_jpy(@item.price)}
          .show-main__content-top__item-box__pricebox__detail
            %span
              (税込)
            %span
              #{@item.delivery_charge.name}
        .show-main__content-top__item-box__item-detail
          #{@item.content}
        .show-main__content-top__item-box__table
          %table
            %tbody
              %tr
                %th
                  出品者
                %td
                  #{@seller.nickname}
                %tr
                  %th
                    カテゴリー
                  %td
                    =link_to "#",class:"kategori" do
                      #{@item.category.root.name}
                    %span <br>＞
                    =link_to "#",class:"kategori" do
                      #{@item.category.parent.name}
                    %span <br>＞
                    =link_to "#",class:"kategori" do
                      #{@item.category.name}
                %tr
                  %th
                    ブランド
                  %td
                    Amazon
                %tr
                  %th
                    発送方法
                  %td
                    #{@item.delivery_method.name}
                %tr
                  %th
                    商品の状態
                  %td
                    #{@item.status.name}
                %tr
                  %th
                    配送料の負担
                  %td
                    #{@item.delivery_charge.name}
                %tr
                  %th
                    配送元の地域
                  %td
                    #{Prefecture.find(@item.prefecture_id).name}
                %tr
                  %th
                    配送日の目安
                  %td
                    #{@item.delivery_days.name}
        .show-main__content-top__item-box__area
          %ul
            .show-main__content-top__item-box__area__optional__btn-left
              %li#linke-btn.show-main__content-top__item-box__area__btn-left__link
                - if user_signed_in? && current_user.id == @item.seller_id
                  %span
                    %icon.far.fa-star
                    お気に入り数：
                    #{@item.bookmarks.count}
                -elsif user_signed_in?
                  -if @item.bookmarked_by?(current_user)
                    %span
                      %icon.fas.fa-star
                      = link_to 'お気に入り解除:', item_bookmarks_path(@item.id) ,method: :delete
                      #{@item.bookmarks.count}
                  -else
                    %span
                      %icon.far.fa-star
                      = link_to 'お気に入り登録：', item_bookmarks_path(@item.id), method: :post
                      #{@item.bookmarks.count}
                - else
                  %span
                    %icon.far.fa-star
                    お気に入り数：
                    #{@item.bookmarks.length}
          %ul.show-main__content-top__item-box__area__optional
            =link_to "#",class:"show-main__content-top__item-box__area__optional__btn-right" do
              %li.show-main__content-top__item-box__area__optional__btn-right__link
                %icon.fa.fa-flag
                不適切な商品の通報

        .show-main__content-top__btn-box
          - if @item.buyer_id.present?
            %buttun{type: "button", class: 'show-buy btn--gray'} 売り切れです
          - else
            - if user_signed_in? && current_user.id == @item.seller_id
              = link_to '商品の編集', edit_item_path(@item), class:'show-edit btn'
              %br or
              = link_to '商品の削除', item_path, method: :delete, class:'show-destroy btn--gray', data: { confirm: "本当に商品を削除してもよろしいですか？" }
            - elsif user_signed_in? && current_user.id != @item.seller_id
              = link_to '商品を購入する', buy_item_path(@item), class:'show-buy btn'
            - else
      .show-main__content-top__comment-box
        - if current_user
          %ul.show-main__content-top__comment-box__coments
          = form_with(model: [@item, @comment], local: true) do |f|
            %input.show-main__content-top__comment-box__coments__input{name:"utf8",type:"hidden",value:""}
            %input.show-main__content-top__comment-box__coments__input{name:"authenticity",type:"hidden",value:""}

            .show-main__content-top__message
              - if @comments
                - @comments.each do |comment|
                  .show-main__content-top__message__box
                    %ul.show-main__content-top__message__box__kaiwa
                      %li.show-main__content-top__message__box__kaiwa__clearfix-messages
                      - if @item.seller_id != comment.user_id
                        .show-main__content-top__message__box__kaiwa__clearfix-messages__name
                          = link_to comment.user.nickname, user_path
                          %figure.show-main__content-top__message__box__kaiwa__clearfix-messages__img-right
                            .show-main__content-top__message__box__kaiwa__clearfix-messages__img-right__name
                            %figcaption.show-main__content-top__message__box__kaiwa__clearfix-messages__img-right__description
                              = image_tag 'yu-za-.jpg', width: '50'
                          .show-main__content-top__message__box__kaiwa__clearfix-messages__text
                            .show-main__content-top__message__box__kaiwa__clearfix-messages__text__right
                              = comment.message
                            .show-main__content-top__message__box__kaiwa__clearfix-messages__text__day
                              = icon('far', 'clock', class: 'icon')
                              %time(datetime="#{comment.created_at}")= time_ago_in_words(comment.created_at)+"前"
                              = link_to item_comment_path(params[:id],comment), method: :delete, class: "btn", data: { confirm: "本当にコメントを削除してもよろしいですか？" } do
                                = icon('fas', 'trash-alt', class: 'trash')
                      - else
                        .show-main__content-top__message__box__kaiwa__clearfix-messages__user
                          = link_to comment.user.nickname
                          .show-main__content-top__message__box__kaiwa__clearfix-messages__img-left
                            %figcaption.show-main__content-top__message__box__kaiwa__clearfix-messages__img-left__description
                              = image_tag 'yu-za-.jpg', width: '50'
                          .show-main__content-top__message__box__kaiwa__clearfix-messages__img-left__text
                            .show-main__content-top__message__box__kaiwa__clearfix-messages__img-left__text__left
                              = comment.message
                            .show-main__content-top__message__box__kaiwa__clearfix-messages__img-left__text__time
                              %id= icon('far', 'clock', class: 'c')
                              %time(datetime="#{comment.created_at}")= time_ago_in_words(comment.created_at)+"前"
                              = link_to item_comment_path(params[:id],comment), method: :delete, class: "btn-d", data: { confirm: "本当にコメントを削除してもよろしいですか？" } do
                                = icon('fas', 'trash-alt', class: 'alt')

            .show-main__content-top__comment-box__coments__p
              コメントは1つの投稿につき50文字以内です。
              %br
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            = f.text_area :message, class:'show-main__content-top__comment-box__coments__textarea'
            = f.submit "コメントする", class: "show-main__content-top__comment-box__coments__button" do
              %i.fas.fa-comment
        - else
          %strong
            %p ※ コメントの投稿には新規登録/ログインが必要です ※
-# appバナー部分テンプレート
=render "appBanner"
-# フッタ部分テンプレート
=render "footer"
-# 出品ボタン部分テンプレート
=render "displayBtn"

app/views/items/t-user-logout.html.haml
.user-logout-header
  部分テンプレートをしようする。
.user-logout
  .user-logout-page.clearfix
    -# 全体
    .user-logout-page__main
      -# メインページ
      .user-logout-page__main__box

        .user-logout-page__main__box__link
          .user-logout-page__main__box__link__btn   
            =link_to"ログアウトの処理",class:"user-logout-page__main__box__link__btn__red" do
              ログアウト

    =render "t-user-show-sidebar"

.user-logout-footer
  部分テンプレートを使用する。

app/views/items/t-user-show.html.haml
.user-show-header
  部分テンプレートをしようする。
.user-show
  .user-show-page.clearfix
    -# 全体
    .user-show-page__main
      -# メインページ
      %section.user-show-page__main__icon
        -# ユーザーアイコン
        =link_to"#",class:"user-show-page__main__icon__link" do
          -# ユーザーボックス
          %figure
            = image_tag "/assets/yu-za-.jpg", alt: "", height: "60", width: "60", class: "user-show-page__main__icon__link__photo"
            -# ユーザーの写真
          %h2.user-show-page__main__icon__link__name
            -# ユーザーの名前
            ピエール
          .user-show-page__main__icon__link__situation
            -# 評価
            %div
              評価
              %span.user-show-page__main__icon__link__situation__good
                0
            %div.good-sukima
              出品数
              %span.user-show-page__main__icon__link__situation__item
                0
      %sction.user-show-page__main__todo
        .user-show-page__main__todo__top-tabs
          -# 追加機能用
        .user-show-page__main__todo__under-tabs
          -# 追加機能用

    =render "t-user-show-sidebar"

.user-show-footer
  部分テンプレートを使用する。

app/views/items/＿form.html.haml
%main.single-main
  %section.sell-container
    .sell-container__inner
      %h2.single-container__head
        商品の情報を入力
      = form_with model: @sell,url:sells_path, class:"sell-container__form", local:true do |f|
            = f.label "商品名"
            = f.text_field :name,class: "sell-content__input input-default", placeholder: "商品名（必須 40文字まで)"
            = f.label "商品の説明"
            = f.text_area :info,class:"sell-content__desc_textarea textarea-default",rows:"5" ,placeholder:"商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
            = f.label "カテゴリー"
            = f.label "商品の状態"
            = f.select :status, Product.statuses.keys, {}, class: "sell-content__select-default"
            = f.label "配送料の負担"
            = f.collection_select :delivery_fee_owner_id, DeliveryFeeOwner.all,:id, :delivery_fee_owner, {prompt: "---"},{class:"sell-content__select-default",id:"delivery_fee_owner"
            //jqueryで:delivery_fee_ownersの値によって表示するセレクトボックスを変動させる。
            = f.label "配送の方法"
            = render partial: 'shipping_method',locals: {delivery_fee_owner_id: DeliveryFeeOwner.first.id}
            = f.label "価格"
            = f.text_field :price, class:"input-default",placeholder:"例）300"
            = f.submit "出品する" ,class:"sell-content__btn-red"