config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy"
  end

  root 'items#index'
  resources :cards, only: [:new, :index, :create, :destroy]
  resources :categories, only: [:index, :show]
  resources :users, only: [:index, :new, :show, :create] do
    member do
      get 'logout'
    end
  end

  namespace :items do
    resources :searches, only: :index
  end

  resources :items do
    resource :bookmarks, only:[:create, :destroy]
    resources :comments, only: [:create, :destroy]
    member do
      get 'buy'
      post 'pay'
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    collection  do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card
  before_action :set_category

  def index
    if @card.present?
      Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(customer.default_card)
      @card_brand = @card_info.brand
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3) 

      case @card_brand
      when "Visa"
        @card_image = "credit-visa.svg"
      when "JCB"
        @card_image = "credit-jcb.svg"
      when "MasterCard"
        @card_image = "credit-master-card.svg"
      when "American Express"
        @card_image = "credit-american_express.svg"
      when "Diners Club"
        @card_image = "credit-dinersclub.svg"
      when "Discover"
        @card_image = "credit-discover.svg"
      when "Saison"
        @card_image = "credit-saison-card.svg"
      end
    end
  end

  def new
    @card = Card.where(user_id: current_user.id).first
    redirect_to cards_url if @card.present?
  end

  def create
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    if params['payjpToken'].blank?
      flash[:notice] = 'クレジットカード登録ができません'
      render "new"
    else
      customer = Payjp::Customer.create(
        description: 'test',
        email: current_user.email,
        card: params['payjpToken'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id)
      if @card.save
        if request.referer&.include?("/registrations/step5")
          redirect_to controller: 'registrations', action: "step6"
        else
          flash[:notice] = '支払い情報の登録が完了しました'
          redirect_to cards_url
        end
      else
        flash[:notice] = 'クレジットカード登録ができません'
        render 'new'
      end
    end
  end

  def destroy
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    if @card.destroy
      flash[:notice] = '削除しました'
      redirect_to cards_url
    else
      flash[:notice] = '削除できませんでした'
      redirect_to cards_url
    end
  end

  private
  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end
  def set_category
    @parents = Category.where(ancestry: nil)
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/cards/_form.html.haml
= form_with url:cards_path, method: :post, html: { name: "inputForm" },class:"form" do |f|
  .form__upper
    .form__upper__group
      = f.label :カード番号
      %span.form-require 必須
      = f.text_field :card_number, name: "card_number", id:"card_number", type: "text", placeholder: '半角数字のみ', class: 'input-default', maxlength: "16"
      %ol
        %li
          %object{type: "image/svg+xml", data: "#{asset_path 'credit-visa.svg'}", width:"35", height:"20"}
        %li
          %object{type: "image/svg+xml", data: "#{asset_path 'credit-master-card.svg'}", width:"35", height:"20"}
        %li
          %object{type: "image/svg+xml", data: "#{asset_path 'credit-saison-card.svg'}", width:"35", height:"20"}
        %li
          %object{type: "image/svg+xml", data: "#{asset_path 'credit-jcb.svg'}", width:"35", height:"20"}
        %li
          %object{type: "image/svg+xml", data: "#{asset_path 'credit-american_express.svg'}", width:"35", height:"20", class:"american_express"}
        %li
          %object{type: "image/svg+xml", data: "#{asset_path 'credit-dinersclub.svg'}", width:"35", height:"20"}
        %li
          %object{type: "image/svg+xml", data: "#{asset_path 'credit-discover.svg'}", width:"35", height:"20"}
    .form__upper__group.exp
      .name
        = f.label :有効期限
        %span.form-require 必須
      = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{}, class: 'input-default harf', name: "exp_month", id:"exp_month"
      %span 月/
      = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]], {}, class: 'input-default harf', name: "exp_year", id:"exp_year"
      %span 年
    .form__upper__group
      = f.label :セキュリティーコード
      %span.form-require 必須
      = f.text_field :cvc, name: "cvc", id:"cvc", class:"cvc", type: "text", placeholder: 'カード背面4桁もしくは3桁の番号', class: 'input-default', maxlength: "16"
    .form__upper__group
      %p.about
        %i.fas.fa-question-circle
        %span
        = link_to 'カード裏面の番号とは？', root_path, class:'about__registered'
    .form__upper__group
      = f.submit 'カード登録', class: 'btn-default', id: "charge-form"

app/views/cards/index.html.haml
=render "items/header"
.mypage-main
  =render "users/sidebar"
  .mypage-main__right
    .mypage-main__right__title
      支払い方法
    .mypage-main__right__content
      .mypage-main__right__content__credit-card
        .mypage-main__right__content__credit-card__title
          クレジットカード一覧
        - if @card.present?
          .mypage-main__right__content__credit-card__content
            .mypage-main__right__content__credit-card__content__info
              = image_tag "#{@card_image}",width:'34',height:'20', alt:'master-card'
              %p.creditcard-info__number
                = "**** **** **** " + @card_info.last4 #クレジットカードの下４桁を表示
              %p.creditcard-info__period 
              = @exp_month + " / " + @exp_year
            = button_to "削除する", card_path(@card), method: :delete, class:"mypage-main__right__content__credit-card__content__delete-btn"
        - else
          .mypage-main__right__content__credit-card__addbtn
            = link_to new_card_path, class:"new-card-btn" do
              %i.far.fa-credit-card
              %span
                クレジットカードを追加する
=render "items/footer"

app/views/cards/new.html.haml
= render 'items/header'
.mypage-main
  = render "users/sidebar"
  .mypage-main__right
    .mypage-main__right__title
      支払い方法
    .mypage-main__right__content
      = render 'form'
      .mypage-main__right__content__explain
        %i.fas.fa-chevron-right
        = link_to '支払い方法について', '#'
= render 'items/footer'